### ISSUE TITLE
Enabeling the "bundled" feature

### ISSUE THREAD

**Issue by dignifiedquire** [stainless-steel/sqlite#20]
I would like to use the `bundled` feature of `sqlite3-src`, but this is not exposed currently. Any chance of adding that?

**Comment by IvanUkhov** [comment]
Please try the following:

```toml
[dependencies.sqlite]
version = "…"
default-features = false
```

[dependencies.sqlite3-sys]
version = "…"
features = ["bundled"]
```
